### ISSUE TITLE
WATHNET integration

### ISSUE THREAD

**Issue by tomalrussell** [nismod/nismod2#132]
Parent issue for WATHNET integration

- [x] #46 output reservoir levels, arc flows
- [x] output levels of restriction, shortfall, requested demand
- [x] #129 input reservoir levels, demand
- [x] input river flows
- [ ] #128 set interventions
- [x] #130 create water_demand model
- [x] Define water zones
- [ ] #131 LAD to water zone adaptor
- [x] Configure realistic default parameter value for per capita water consumption
- [x] #133 scenario input for non-public demand at catchment scale
- [x] Only run consecutive years - in wrapper check previous timestep - current timestep
- [x] CSV of reservoir name / capacity
- [x] Initialise reservoirs at full
