### ISSUE TITLE
Digital integration (mobile)

### ISSUE THREAD

**Issue by tomalrussell** [nismod/nismod2#141]
- [x] Configure inputs (population, data growth) for mobile model
- [x] Configure parameters for mobile model
- [x] Downscaling adaptor to postcode sector population
- [x] Wrapper for mobile model
- [ ] Port decision script for mobile model
- [ ] Configure arc runs for mobile model
