### ISSUE TITLE
Digital integration (fixed)

### ISSUE THREAD

**Issue by willu47** [nismod/nismod2#55]
Integration of the digital communications models consists of the following steps broken down into individual issues

- [ ] Setup configuration for fixed model #53 
- [ ] Test integration for fixed model #40 
- [ ] Pre-specified planning interventions for fixed model #38 
- [ ] Developing a rule-based decision heuristic to replace the one currently used in the fixed model #39
